services:
  postgres:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_DB: ${DATABASE__POSTGRES_DB}
      POSTGRES_USER: ${DATABASE__POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE__POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      TZ: "Europe/Moscow"
    env_file: .env
    restart: "unless-stopped"
    volumes:
      - tg-assistan-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  redis:
    image: redis:7.4.2-alpine3.21
    restart: "unless-stopped"
    volumes: 
      - redis-data:/data

  reminder:
    build: 
      dockerfile: scheduler.dockerfile
    command: sh ./schedule_entrypoint.sh
    env_file: .env
    depends_on:
      - redis
    restart: "unless-stopped"

  tg_assisnant:
    build: 
      dockerfile: bot.dockerfile
    command: sh ./entrypoint.sh
    env_file: .env
    depends_on:
      - postgres
    restart: "unless-stopped"

volumes:
  tg-assistan-data:
  redis-data:
