"""change repeat enum

Revision ID: 9549a6aca82d
Revises: c7b72be727f2
Create Date: 2025-04-09 16:14:39.772465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '9549a6aca82d'
down_revision: Union[str, None] = 'c7b72be727f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='event_repeat_intervals',
        new_values=['DAILY', 'WEEKLY', 'MONTHLY', 'SIXMONTH', 'YEARLY'],
        affected_columns=[TableReference(table_schema='public', table_name='event', column_name='repeat_interval')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='event_repeat_intervals',
        new_values=['DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY'],
        affected_columns=[TableReference(table_schema='public', table_name='event', column_name='repeat_interval')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
